### ISSUE TITLE
Short delay when setting bpm via $ self operator

### ISSUE THREAD

**Issue by bbarham** [hundredrabbits/Orca#187]
I've figured I can do a swung/shuffled clock like so:
```
....C2...
D1..02T98
.$bpm:80.
```
And this works reasonably well, but I tried this:
```
D1......
.$bpm:80
```
and this
```
D0......
.$bpm:80
```
Which should produce identical output, but reseting the bpm on each frame results in a slower overall speed. I tested this on v215 Mac sending a midi note each frame to Renoise so otherwise, no noticeable jitter. This short delay might by unavoidable, but being able to do these types of timing manipulations accurately within Orca would be very powerful.

**Comment by neauoire** [comment]
I'll try it out :)

**Comment by neauoire** [comment]
Maybe a global swing percentage might be fun.

**Comment by neauoire** [comment]
I noticed the problem too. I don't think I know of a way to handle this properly at this time.
I've just pushed a little update that tries to address that problem tho, could you have a look and see if that changes anything for you?

**Comment by bbarham** [comment]
Thank you for looking in to this. Your change does help with cpu usage when there is no bpm difference, but I do still see the delay when alternating between two bpms. I'm going to do some more reading about this and see if there's anything I can do.
